import img from "../../../assets/Country/wepik-export-20231005065307oqGb.png";
import banner1 from "../../../assets/Country/wepik-export-20231005074933PrgR.png";
import banner2 from "../../../assets/Country/wepik-export-20231005075036QJp1.png";
import banner3 from "../../../assets/Country/wepik-export-20231005075159MoW6.png";
import banner4 from "../../../assets/Country/wepik-export-20231005075235vukH.png";

export const Countries = [
  {
    id: 1,
    countryName: "United States",
    url: img,
    banner: banner1,
    university: [
      {
        id: 1,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 2,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 3,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 4,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 5,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 6,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 7,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 8,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 9,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
    ],
    details:
      "সুইেডেনে একজন আন্তজার্তিক ছাত্র হিসেবে, আপনাকে  আপনার পড়াশোনার পাশাপাশি কাজ করার অনুমতি   েদওয়া হয়েছে - আপনি কত ঘন্টা কাজ করতে পারবেন তার  েকান সরকারী সীমাবদ্ধতা  েনই।",
  },
  {
    id: 2,
    countryName: "Canada",
    url: img,
    banner: banner2,
    university: [
      {
        id: 1,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 2,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 3,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 4,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 5,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 6,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 7,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 8,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 9,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
    ],
    details:
      "সুইেডেনে একজন আন্তজার্তিক ছাত্র হিসেবে, আপনাকে  আপনার পড়াশোনার পাশাপাশি কাজ করার অনুমতি   েদওয়া হয়েছে - আপনি কত ঘন্টা কাজ করতে পারবেন তার  েকান সরকারী সীমাবদ্ধতা  েনই।",
  },
  {
    id: 3,
    countryName: "UK",
    url: img,
    banner: banner3,
    university: [
      {
        id: 1,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 2,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 3,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 4,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 5,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 6,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 7,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 8,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 9,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
    ],
    details:
      "সুইেডেনে একজন আন্তজার্তিক ছাত্র হিসেবে, আপনাকে  আপনার পড়াশোনার পাশাপাশি কাজ করার অনুমতি   েদওয়া হয়েছে - আপনি কত ঘন্টা কাজ করতে পারবেন তার  েকান সরকারী সীমাবদ্ধতা  েনই।",
  },
  {
    id: 4,
    countryName: "DenMark",
    url: img,
    banner: banner4,
    university: [
      {
        id: 1,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 2,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 3,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 4,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 5,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 6,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 7,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 8,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
      {
        id: 9,
        universityName: "United States Florida west",
        IeltsScore: "7.0",
        varsityLink: "https://uwf.edu/",
        CourseTitle:
          "Master's Programme in Additive Manufacturing,120 credits (TAT2M)",
        Program: "Master's",
        Course: "Manufacturing",
        Credit: "120",
        deadline: "09/10/2023",
        mapLink: "https://maps.app.goo.gl/Z54fwCty44fUEAyZ7",
      },
    ],
    details:
      "সুইেডেনে একজন আন্তজার্তিক ছাত্র হিসেবে, আপনাকে  আপনার পড়াশোনার পাশাপাশি কাজ করার অনুমতি   েদওয়া হয়েছে - আপনি কত ঘন্টা কাজ করতে পারবেন তার  েকান সরকারী সীমাবদ্ধতা  েনই।",
  },
];
